image: ubuntu/lts
packages:
  - rust-all
  - pkg-config
sources:
  - https://git.sr.ht/~gigablaster/dess-engine
tasks:
  - format: |
      cd dess-engine
      cargo fmt -- --check
  - clippy: |
      cd dess-engine
      cargo clippy --all-targets -- -D warnings
  - build: |
      cd dess-engine
      cargo build
  - test: |
      cd dess-engine
      cargo test