image: archlinux
packages:
  - rust
sources:
  - https://git.sr.ht/~gigablaster/dess-engine
tasks:
  - format: |
      cd dess-engine
      cargo fmt -- --check
  - clippy: |
      cd dess-engine
      cargo clippy --locked --all-targets -- -D warnings
  - test: |
      cd dess-engine
      cargo check --locked --all-targets --all-features
      cargo test --locked --all-targets --all-features