[workspace]
members = [
    "crates/lib/common",
    "crates/lib/backend",
    "crates/lib/assets",
    "crates/lib/asset-pipeline",
    "crates/lib/runner",
    "crates/bin/builder",
]

resolver = "2"
