[package]
name = "render"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
render-backend = { path = "../render-backend" }
ash = "0.37"
common = { path = "../common" }
log = "0.4"
simple_logger = "4.0"
anyhow = "1.0"
puffin = "0.15"
gpu-allocator = { version = "0.22", default-features = false, features = ["vulkan"]}
