
[package]
name = "resources"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
log = "0.4"
uuid = "1.3"
four-cc = "0.2"
byteorder = "1.4"
image = "0.24"
