[package]
name = "render-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.37"
sdl2 = { version = "0.35", features = ["bundled"] }
common = { path = "../common" }
log = "0.4"
simple_logger = "4.0"
anyhow = "1.0"
puffin = "0.14"
gpu-allocator = { version = "0.22", default-features = false, features = ["vulkan"]}
arrayvec = "0.7"

[dev-dependencies]
runner = { path = "../runner" }

[[example]]
name = "vk-clear"
