[package]
name = "dess-builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dess-asset-pipeline = { path = "../../lib/asset-pipeline" }
dess-assets = { path = "../../lib/assets" }
bevy_tasks = { version = "0.12.1", features = ["multi-threaded"] }
log = "0.4.20"
simple_logger = "4.2.0"
